### PR TITLE
Issue 100 - bug fixes and customer feedback on breeds page

### LINKED ISSUE #100: [QA] Breed Pages
https://main--petplace--hlxsites.hlx.live/article/breed/pembroke-welsh-corgi

- [x] Content in “Physical Characteristics” section is centered instead of lined up on the lefthand side.
- [x] Internal links and Facts section are still being implemented on AEM side.
- [x] Galaxy Fold: Other Breeds to Explore and References cut off.

Image

- [x] large white space on the bottom of the "Care" carousel 
- [x] On opening the accordion, the bottom padding is missing from the paragraph copy and is touching the border

Image

- [x] The page is also using a different footer format in comparison with other blog articles

- [x] Cat image near footer

### PR DESCRIPTION
**Pull request by travrob1**
Breed page bugs
Fix #100 

Test URLs:
- Before: https://main--petplace--hlxsites.hlx.page/article/breed/pembroke-welsh-corgi
- After: https://issue-100--petplace--hlxsites.hlx.page/article/breed/pembroke-welsh-corgi

### CODE REVIEW

File: templates/breed-page/breed-page.js [hunk 1]
```diff
@@ -1,6 +1,6 @@
 import {
   getMetadata,
-  decorateIcons,
+  decorateIcons, createOptimizedPicture,
```
Comment (ramboz) [inline templates/breed-page/breed-page.js:3]:
```suggestion
  decorateIcons,
  createOptimizedPicture,
```

**Review by ramboz — APPROVED** [review]
