### PR TITLE
fix:Position of ToC block relative to disclosure block

### LINKED ISSUE #213: Position of ToC block relative to disclosure block
#### 14. **Content order** issue

Petplace | Hlx.live
-- | --
https://www.petplace.com/article/general/news/new-york-banning-retail-pet-sales-puppy-mills/ | https://main--petplace--hlxsites.hlx.live/article/general/news/new-york-banning-retail-pet-sales-puppy-mills
Screenshot 2023-06-30 at 12 03 10 AM

_Originally posted by @FentPams in https://github.com/hlxsites/petplace/issues/197#issuecomment-1614814514_

### PR DESCRIPTION
**Pull request by FentPams**
Fix #213 

Test URLs:
- Before: https://main--petplace--hlxsites.hlx.live/article/general/news/new-york-banning-retail-pet-sales-puppy-mills
- After: https://issue-213--hlxsites.hlx.live/article/general/news/new-york-banning-retail-pet-sales-puppy-mills
Screenshot 2023-07-05 at 10 36 58 AM

### CODE REVIEW

File: templates/article-page/article-page.js [hunk 1]
```diff
@@ -29,7 +29,14 @@ function createTableOfContents(main) {
   }
   const tocDiv = document.createElement('div');
   tocDiv.classList.add('toc');
-  main.querySelector('h1').after(tocDiv);
+
+  // if there is a disclosure, add the toc after it, otherwise add it after the h1
+  const disclosure = main.querySelector('.disclosure');
```
Comment (ramboz) [inline templates/article-page/article-page.js:34]: The disclosure is sometimes at the end of the page, so I think it's best to check if there is a disclosure AND it is the first element in the article

**Review by ramboz — CHANGES_REQUESTED** [review]

**Review by ramboz — APPROVED** [review]
